extends Node2D

signal addPoints(value:int)
signal garageUI(value:bool)
signal upgradeUnlock(value:int)
signal dialogueText(text:String)
signal removePixel(positionX:float, positionY:float)
signal setupGameProgress(totalGrass:int)
signal removeGrass()
signal halfway()
signal hideTrailer(enable:bool)
signal houseDamage(value:int)
signal loseGame()
signal winGame()
signal shoot()
signal startWave(difficulty:int)
signal endWave()
signal volume(enabled:bool)
signal playerPosition(pos:Vector2)
